### ISSUE TITLE
Error in saving svg

### ISSUE THREAD

**Issue by ghost** [almiheenko/AGB#1]
Hello,
saving the graph in svg saves a faulty svg file 
This is the error in the svg

`error on line 3 at column 9: Extra content at the end of the document`
thank you

**Comment by almiheenko** [comment]
Hello,

Thanks for reporting the issue! I fixed it in the master branch and also updated the conda package. Please let me know if there are any issues.

Best regards,
Alla

**Comment by ghost** [comment]
Hello,
sorry for the very very late feedback I am just reusing it now. I reinstalled it with conda but still can't get a workable svg. 
`Error domain 1 code 5 on line 3 column 9 of file:///home/alessandro/Downloads/graph.svg: Extra content at the end of the document`
